### ISSUE TITLE
How to associate chunks and offsets?

### ISSUE THREAD

**Issue by devinivy** [indutny/json-depth-stream#1]
I'm interested in streaming JSON from a web service to transform array items as they arrive over the wire.  I love that this parser can handle depth, because I would not necessarily like to parse each individual array item.  I just want to get a hold of the string/buffer of each individual (parse-able but not parsed) array item.  This library appears to provide offsets but there's no obvious way to get at the chunks themselves or, for example, to know which chunks the offsets provided by `split` refer to.

To achieve what I'm talking about, is it safe to use the explicit stream-once usage and assume that when `update(chunk)` is called, `split`/`visit` events will be fired synchronously, all for the data in `chunk`?

**Comment by indutny** [comment]
Hello!

`update()` is synchronous indeed! `split`/`visit` will be invoked before it will end, so you may use this to figure out what particular chunk they are talking about.

Apparently documentation is quite lacking on this. I'd appreciate any help!

Hope this helps,
Fedor.

**Comment by devinivy** [comment]
This helps a lot– thanks!  I plan to PR the docs when I get a chance.

**Comment by indutny** [comment]
Thanks!
