### ISSUE TITLE
Is there an any key?

### ISSUE THREAD

**Issue by brandonmp** [indutny/json-depth-stream#3]
I'd like to query @ 3-levels deep, returning every key with a path like `users/${uid}/firstName`

I've tried `true` and `'*'`, but no dice

**Comment by indutny** [comment]
Hello!

I'm not quite sure where you tried to pass `true` or `*`. Could you please quote what you tried?

Thanks,
Fedor.

**Comment by brandonmp** [comment]
Oh good point! Here's a better snippet. the use case here is to extract all values at `users.*.phone`.  This is similar to `JSONStream` syntax, but your library seems much faster so I'd rather use it. 


```
// data.json
{
    users: {
        user1: {
            name:  "Steve",
            phone: 123
        },
        user2: {
            name: "Paul"
            phone: 321
        },
        // ...
   }
}

// fetch-phone-numbers.js
...
const query = json.query(['users', '*', 'phone'])
readStream
  .pipe(json)
  .pipe(writeStream)


// results.json - what I hope to end up with
{
    users: {
        user1: {
            phone: 123
        },
        user2: {
            phone: 321
        },
        // ...
}
}

// 
     
```

**Comment by indutny** [comment]
Oh, `query()`. Got it now!

Sorry, there is no API to do this in this repo. Query effectively looks up particular key.

Technically, there is no reason to not support wildcards, but they don't fit into current API. If you have any suggestions for new APIs - I'll be glad to discuss them.
